// quotes.js
// A modest set of love messages. You can edit or expand this list.
const QUOTES = [
  "I love you more than words can say.",
  "You are my today and all of my tomorrows.",
  "In you, I've found the love of my life and my closest, truest friend.",
  "My heart is and always will be yours.",
  "You make my heart smile.",
  "I fall in love with you every single day.",
  "Where there is love, there is life.",
  "You are the reason I believe in love.",
  "Your hand fits in mine like it was made just for me.",
  "I still get butterflies even though I've seen you a hundred times.",
  "Every moment with you is a treasure.",
  "I choose you. And I’ll choose you over and over and over.",
  "I love you more than I have ever found a way to say to you.",
  "You are my favorite notification.",
  "You make my soul sing.",
  "With you, forever won’t be long enough.",
  "You are my sun, my moon, and all my stars.",
  "I didn't choose you, my heart did.",
  "Home is wherever I'm with you.",
  "You're the piece of me I didn't know was missing.",
  "I love the way you make me feel.",
  "Your smile is literally the cutest thing I've ever seen.",
  "To the world you may be one person, but to one person you are the world.",
  "I am catastrophically in love with you.",
  "Thank you for being my today and all of my tomorrows.",
  "Every love story is beautiful, but ours is my favorite.",
  "I will always choose you.",
  "You are the best thing that's ever been mine.",
  "I can't imagine my life without you in it.",
  "You're my favorite place to go when my mind searches for peace.",
  "I love you not only for what you are, but for what I am when I am with you.",
  "Your love is the anchor of my life.",
  "Being in your arms is my happy place.",
  "I never want to stop making memories with you.",
  "My heart is perfect because you are inside.",
  "I didn't know what I wanted until I met you.",
  "You are my once-in-a-lifetime.",
  "You are the poem I never knew how to write, and this life is the story I always wanted to tell.",
  "I want to be with you until my last page.",
  "Loving you is the easiest thing I've ever done.",
  "I love you — and that's the beginning and end of everything.",
  "When I'm with you, hours feel like seconds. When we're apart, days feel like years.",
  "If I had to choose between breathing and loving you I would use my last breath to say I love you.",
  "You are my favorite hello and my hardest goodbye.",
  "I still remember the first time I saw you. My heart whispered, 'That's the one.'",
  "You are the love that came without warning; you had my heart before I could say no.",
  "My favorite fairy tale is our love story.",
  "I love you more than coffee, but please don't make me prove it.",
  "You are the argument I never want to win because peace with you is better.",
  "Every day I love you more. Today more than yesterday and less than tomorrow.",
  "Your voice is my favorite sound.",
  "There is no remedy for love but to love more.",
  "I give you my heart and I promise to keep it safe.",
  "You are my greatest adventure.",
  "Your love is a melody that plays softly in my heart.",
  "Stay with me and I'll make you believe in magic.",
  "You make even the ordinary moments extraordinary.",
  "If kisses were snowflakes, I'd send you a blizzard.",
  "You are the smile I want to see every morning.",
];

// Expose a simple paging function
const QUOTES_PER_PAGE = 12;
function getQuotesPage(page = 0){
  const start = page * QUOTES_PER_PAGE;
  return QUOTES.slice(start, start + QUOTES_PER_PAGE);
}

